### ISSUE TITLE
Import with no classes backing it...

### ISSUE THREAD

**Issue by HakAl** [bytehala/dagger2-gradle-quickstart#1]
![seered](https://cloud.githubusercontent.com/assets/5837644/7768883/79faa912-004d-11e5-9be3-d604e95f8d81.png)

import com.noobgrammer.dagger2gradlequickstartexample.dagger.components.DaggerApplicationComponent;

You import this into the Application class. This class doesn't exist in the project, I've seen this in every recent Dagger 2 project and don't get it. I can't switch to Dagger 2 because I can't figure out what this is. And neither can Android Studio.. haha

I figured it out. Just glanced at Javadoc for Component and saw the class is generated, so I built the project and PRESTO!

**Comment by bytehala** [comment]
Yes, that's how Dagger 2 works, it has code generation which helps developers follow the code. This is one of the things that's majorly different from Dagger 1, but it's really nifty! I mention this in [Step 3](https://github.com/bytehala/dagger2-gradle-quickstart/commit/8fb2521269ec192daeb13e34e833d39d355924fb) of the commit messages.

Closing this issue then. =)
