### ISSUE TITLE
Why butter knife?

### ISSUE THREAD

**Issue by thupten1234** [bytehala/dagger2-gradle-quickstart#3]
If butterknife is not related to dagger2, I wish you did not include it.

**Comment by thupten1234** [comment]
I guess i could learn butterknife. It seems simple to use. http://jakewharton.github.io/butterknife/

**Comment by bytehala** [comment]
_Just adding my thoughts, in case others raise the same question..._
Yes, actually Butterknife is prevalent in the industry, and it is encouraged by the rockstars of Android.
Good luck!
